const clientNameList = [
  "Accurate Interpreting",
  "Advanced Pain Control",
  "ADVANTGARDE MEDICAL INC.",
  "Adventgarde",
  "Allan Delman MD",
  "Avalon Family Medical Group",
  "Bazan Huerta & Associates",
  "Comprehensive Interpreting",
  "Cosmopolitan Translators, LLC",
  "Cosmopolitan Translators, LLC",
  "Daniel M Zinar MD",
  "Electrotherapeutics, Inc.",
  "Enhanced Precision Care",
  "Enterprise Interpreting LLC",
  "Gabriel Rubanenko MD - Wilshire",
  "Galaxy Medical Center",
  "Gennady Musher, M.D.",
  "Glendale Urgency Chiropractic Clinic c/o New Era General Services",
  "Industrial Interpreting LLC",
  "Innovative Translation, LLC",
  "Innovative Translation, LLC",
  "Insomnia Medical Center - North Hollywood",
  "Insomnia Medical Center - W Hollywood",
  "Insomnia Medical Center - Wilshire",
  "Insomnia Medical Center -East LA",
  "Insomnia Medical Center, Inc c/o New Era",
  "JAM Medical Equipment",
  "James Schmidt MD",
  "LA Mediwave",
  "Lavi Spine & Orthopedic Medical Center",
  "MBA Psychiatric Services, Inc.",
  "Narbonne Medical Group",
  "National Duramed LLC",
  "Nationwide Interpreting",
  "New Era General Services, Inc.",
  "New Pain Relief",
  "Non Invasive Therapeutics",
  "ORTHO AVR",
  "Orthopaedic Surgery Spine Surgery- Allen Delman MD.",
  "Pacific Harbor Medical Group Inc",
  "Pacific Orthopedic & Rehab - North Hollywood",
  "Pacific Orthopedics & Rehab - East LA",
  "Pacific Orthopedics & Rehab - Wilshire",
  "Pain Control Solution",
  "Precise Interpreting ",
  "Precision Bone and Joint Specialist",
  "Premium Interpreting ",
  "QBC QUALIFIED BILLING & COLLECTIONS, LLC.",
  "Selective Diagnostics, Inc.",
  "South Lake Medical Center",
  "Spine & Orthopedic Specialist c/o Lavie Spine & Orthopedic Medical Center",
  "The Law Office Of Michael Saint George",
  "The Spine Institute",
  "Tristar Wilshire Orthopedics and Rehabilitation",
  "Ultimate Pain Relief",
  "Universal Translation Services, Valley Spine Center / The Spine Institute",
  "Vanguard North Hollywood",
  "Vanguard Psychiatric - Wilshire",
  "Vanguard Psychiatric East LA",
  "West Coast Interpreting",
  "West Coast Occupational Medical Group",
  "Westside Wilshire Medical Group",
  "Willow Medical Group",
  "Willow Medical Group c/o Innovative Medical Management",
];

export default clientNameList;
